//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Oagis.CodeLists {
    using System.Xml.Serialization;
    using System.Xml.Linq;
    
    public interface Namespace
    {
        const string URI = "http://www.openapplications.org/oagis/9/codelists";
        public readonly static XNamespace XNAMESPACE;

        static Namespace() {
            XNAMESPACE = XNamespace.Get(URI);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openapplications.org/oagis/9/codelists")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openapplications.org/oagis/9/codelists", IsNullable=false)]
    public partial class GenSupportCodeLists {
        
        private ActionCodeEnumerationType actionCodeEnumerationTypeSupportField;
        
        private string actionCodeContentTypeSupportField;
        
        private string currencyCodeContentTypeSupportField;
        
        private string languageCodeContentTypeSupportField;
        
        private string mIMECodeContentTypeSupportField;
        
        private ResponseActionCodeEnumerationType responseActionCodeEnumerationTypeSupportField;
        
        private string responseActionCodeContentTypeSupportField;
        
        private ResponseCodeEnumerationType responseCodeEnumerationTypeSupportField;
        
        private string responseCodeContentTypeSupportField;
        
        private string stateCodeEnumerationTypeSupportField;
        
        private string stateCodeContentTypeSupportField;
        
        private SystemEnvironmentCodeEnumerationType systemEnvironmentCodeEnumerationTypeSupportField;
        
        private string systemEnvironmentCodeContentTypeSupportField;
        
        private string unitCodeContentTypeSupportField;
        
        private CurrencyCode.CurrencyCodeType clm54217CurrencyCodeTypeSupportField;
        
        private CurrencyCode.CurrencyCodeContentType clm54217CurrencyCodeContentTypeSupportField;
        
        private LanguageCode.LanguageCodeType languageCodeTypeSupportField;
        
        private string clm5639LanguageCodeContentTypeSupportField;
        
        private IanaMimeMediaTypes.BinaryObjectMimeCodeType binaryObjectMimeCodeTypeSupportField;
        
        private string binaryObjectMimeCodeContentTypeSupportField;
        
        private UnitCode.UnitCodeType unitCodeTypeSupportField;
        
        private string clm66411UnitCodeContentTypeSupportField;
        
        /// <remarks/>
        public ActionCodeEnumerationType ActionCodeEnumerationTypeSupport {
            get {
                return this.actionCodeEnumerationTypeSupportField;
            }
            set {
                this.actionCodeEnumerationTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ActionCodeContentTypeSupport {
            get {
                return this.actionCodeContentTypeSupportField;
            }
            set {
                this.actionCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCodeContentTypeSupport {
            get {
                return this.currencyCodeContentTypeSupportField;
            }
            set {
                this.currencyCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCodeContentTypeSupport {
            get {
                return this.languageCodeContentTypeSupportField;
            }
            set {
                this.languageCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string MIMECodeContentTypeSupport {
            get {
                return this.mIMECodeContentTypeSupportField;
            }
            set {
                this.mIMECodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseActionCodeEnumerationType ResponseActionCodeEnumerationTypeSupport {
            get {
                return this.responseActionCodeEnumerationTypeSupportField;
            }
            set {
                this.responseActionCodeEnumerationTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseActionCodeContentTypeSupport {
            get {
                return this.responseActionCodeContentTypeSupportField;
            }
            set {
                this.responseActionCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseCodeEnumerationType ResponseCodeEnumerationTypeSupport {
            get {
                return this.responseCodeEnumerationTypeSupportField;
            }
            set {
                this.responseCodeEnumerationTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeContentTypeSupport {
            get {
                return this.responseCodeContentTypeSupportField;
            }
            set {
                this.responseCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string StateCodeEnumerationTypeSupport {
            get {
                return this.stateCodeEnumerationTypeSupportField;
            }
            set {
                this.stateCodeEnumerationTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string StateCodeContentTypeSupport {
            get {
                return this.stateCodeContentTypeSupportField;
            }
            set {
                this.stateCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SystemEnvironmentCodeEnumerationType SystemEnvironmentCodeEnumerationTypeSupport {
            get {
                return this.systemEnvironmentCodeEnumerationTypeSupportField;
            }
            set {
                this.systemEnvironmentCodeEnumerationTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string SystemEnvironmentCodeContentTypeSupport {
            get {
                return this.systemEnvironmentCodeContentTypeSupportField;
            }
            set {
                this.systemEnvironmentCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string UnitCodeContentTypeSupport {
            get {
                return this.unitCodeContentTypeSupportField;
            }
            set {
                this.unitCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyCode.CurrencyCodeType clm54217CurrencyCodeTypeSupport {
            get {
                return this.clm54217CurrencyCodeTypeSupportField;
            }
            set {
                this.clm54217CurrencyCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyCode.CurrencyCodeContentType clm54217CurrencyCodeContentTypeSupport {
            get {
                return this.clm54217CurrencyCodeContentTypeSupportField;
            }
            set {
                this.clm54217CurrencyCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public LanguageCode.LanguageCodeType LanguageCodeTypeSupport {
            get {
                return this.languageCodeTypeSupportField;
            }
            set {
                this.languageCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string clm5639LanguageCodeContentTypeSupport {
            get {
                return this.clm5639LanguageCodeContentTypeSupportField;
            }
            set {
                this.clm5639LanguageCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public IanaMimeMediaTypes.BinaryObjectMimeCodeType BinaryObjectMimeCodeTypeSupport {
            get {
                return this.binaryObjectMimeCodeTypeSupportField;
            }
            set {
                this.binaryObjectMimeCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string BinaryObjectMimeCodeContentTypeSupport {
            get {
                return this.binaryObjectMimeCodeContentTypeSupportField;
            }
            set {
                this.binaryObjectMimeCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public UnitCode.UnitCodeType UnitCodeTypeSupport {
            get {
                return this.unitCodeTypeSupportField;
            }
            set {
                this.unitCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string clm66411UnitCodeContentTypeSupport {
            get {
                return this.clm66411UnitCodeContentTypeSupportField;
            }
            set {
                this.clm66411UnitCodeContentTypeSupportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/codelists")]
    public enum ActionCodeEnumerationType {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Modified,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/codelists")]
    public enum ResponseActionCodeEnumerationType {
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Modified,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/codelists")]
    public enum ResponseCodeEnumerationType {
        
        /// <remarks/>
        Always,
        
        /// <remarks/>
        OnError,
        
        /// <remarks/>
        Never,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/codelists")]
    public enum SystemEnvironmentCodeEnumerationType {
        
        /// <remarks/>
        Production,
        
        /// <remarks/>
        Test,
    }
}
