//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Oagis.UnqualifiedDataTypes {
    using System.Xml.Serialization;
    using System.Xml.Linq;
    
    public interface Namespace
    {
        const string URI = "http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1";
        public readonly static XNamespace XNAMESPACE;

        static Namespace() {
            XNAMESPACE = XNamespace.Get(URI);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1", IsNullable=false)]
    public partial class GenSupportUnqualifiedDataTypes {
        
        private AmountType amountTypeSupportField;
        
        private BinaryObjectType binaryObjectTypeSupportField;
        
        private GraphicType graphicTypeSupportField;
        
        private PictureType pictureTypeSupportField;
        
        private SoundType soundTypeSupportField;
        
        private VideoType videoTypeSupportField;
        
        private CodeType codeTypeSupportField;
        
        private IdentifierType identifierTypeSupportField;
        
        private MeasureType measureTypeSupportField;
        
        private QuantityType quantityTypeSupportField;
        
        private TextType textTypeSupportField;
        
        private NameType nameTypeSupportField;
        
        private System.DateTime dateTimeTypeSupportField;
        
        private System.DateTime dateTypeSupportField;
        
        private System.DateTime timeTypeSupportField;
        
        private bool indicatorTypeSupportField;
        
        private decimal numericTypeSupportField;
        
        private decimal valueTypeSupportField;
        
        private decimal percentTypeSupportField;
        
        private decimal rateTypeSupportField;
        
        /// <remarks/>
        public AmountType AmountTypeSupport {
            get {
                return this.amountTypeSupportField;
            }
            set {
                this.amountTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public BinaryObjectType BinaryObjectTypeSupport {
            get {
                return this.binaryObjectTypeSupportField;
            }
            set {
                this.binaryObjectTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public GraphicType GraphicTypeSupport {
            get {
                return this.graphicTypeSupportField;
            }
            set {
                this.graphicTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public PictureType PictureTypeSupport {
            get {
                return this.pictureTypeSupportField;
            }
            set {
                this.pictureTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SoundType SoundTypeSupport {
            get {
                return this.soundTypeSupportField;
            }
            set {
                this.soundTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public VideoType VideoTypeSupport {
            get {
                return this.videoTypeSupportField;
            }
            set {
                this.videoTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public CodeType CodeTypeSupport {
            get {
                return this.codeTypeSupportField;
            }
            set {
                this.codeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType IdentifierTypeSupport {
            get {
                return this.identifierTypeSupportField;
            }
            set {
                this.identifierTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public MeasureType MeasureTypeSupport {
            get {
                return this.measureTypeSupportField;
            }
            set {
                this.measureTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public QuantityType QuantityTypeSupport {
            get {
                return this.quantityTypeSupportField;
            }
            set {
                this.quantityTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public TextType TextTypeSupport {
            get {
                return this.textTypeSupportField;
            }
            set {
                this.textTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public NameType NameTypeSupport {
            get {
                return this.nameTypeSupportField;
            }
            set {
                this.nameTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTimeTypeSupport {
            get {
                return this.dateTimeTypeSupportField;
            }
            set {
                this.dateTimeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateTypeSupport {
            get {
                return this.dateTypeSupportField;
            }
            set {
                this.dateTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime TimeTypeSupport {
            get {
                return this.timeTypeSupportField;
            }
            set {
                this.timeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public bool IndicatorTypeSupport {
            get {
                return this.indicatorTypeSupportField;
            }
            set {
                this.indicatorTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumericTypeSupport {
            get {
                return this.numericTypeSupportField;
            }
            set {
                this.numericTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValueTypeSupport {
            get {
                return this.valueTypeSupportField;
            }
            set {
                this.valueTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentTypeSupport {
            get {
                return this.percentTypeSupportField;
            }
            set {
                this.percentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public decimal RateTypeSupport {
            get {
                return this.rateTypeSupportField;
            }
            set {
                this.rateTypeSupportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class AmountType {
        
        private string currencyIDField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currencyID {
            get {
                return this.currencyIDField;
            }
            set {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class BinaryObjectType {
        
        private string formatField;
        
        private string mimeCodeField;
        
        private string encodingCodeField;
        
        private string characterSetCodeField;
        
        private string uriField;
        
        private string filenameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeCode {
            get {
                return this.mimeCodeField;
            }
            set {
                this.mimeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string encodingCode {
            get {
                return this.encodingCodeField;
            }
            set {
                this.encodingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string characterSetCode {
            get {
                return this.characterSetCodeField;
            }
            set {
                this.characterSetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class GraphicType {
        
        private string formatField;
        
        private string mimeCodeField;
        
        private string encodingCodeField;
        
        private string uriField;
        
        private string filenameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeCode {
            get {
                return this.mimeCodeField;
            }
            set {
                this.mimeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string encodingCode {
            get {
                return this.encodingCodeField;
            }
            set {
                this.encodingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class PictureType {
        
        private string formatField;
        
        private string mimeCodeField;
        
        private string encodingCodeField;
        
        private string uriField;
        
        private string filenameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeCode {
            get {
                return this.mimeCodeField;
            }
            set {
                this.mimeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string encodingCode {
            get {
                return this.encodingCodeField;
            }
            set {
                this.encodingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class SoundType {
        
        private string formatField;
        
        private string mimeCodeField;
        
        private string encodingCodeField;
        
        private string uriField;
        
        private string filenameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeCode {
            get {
                return this.mimeCodeField;
            }
            set {
                this.mimeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string encodingCode {
            get {
                return this.encodingCodeField;
            }
            set {
                this.encodingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class VideoType {
        
        private string formatField;
        
        private string mimeCodeField;
        
        private string encodingCodeField;
        
        private string uriField;
        
        private string filenameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeCode {
            get {
                return this.mimeCodeField;
            }
            set {
                this.mimeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string encodingCode {
            get {
                return this.encodingCodeField;
            }
            set {
                this.encodingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.CodeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class CodeType {
        
        private string listIDField;
        
        private string listAgencyIDField;
        
        private string listAgencyNameField;
        
        private string listNameField;
        
        private string listVersionIDField;
        
        private string nameField;
        
        private string languageIDField;
        
        private string listURIField;
        
        private string listSchemeURIField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencyName {
            get {
                return this.listAgencyNameField;
            }
            set {
                this.listAgencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listURI {
            get {
                return this.listURIField;
            }
            set {
                this.listURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listSchemeURI {
            get {
                return this.listSchemeURIField;
            }
            set {
                this.listSchemeURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.IdentifierType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class IdentifierType {
        
        private string schemeIDField;
        
        private string schemeNameField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencyNameField;
        
        private string schemeVersionIDField;
        
        private string schemeDataURIField;
        
        private string schemeURIField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeName {
            get {
                return this.schemeNameField;
            }
            set {
                this.schemeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeAgencyName {
            get {
                return this.schemeAgencyNameField;
            }
            set {
                this.schemeAgencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string schemeVersionID {
            get {
                return this.schemeVersionIDField;
            }
            set {
                this.schemeVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string schemeDataURI {
            get {
                return this.schemeDataURIField;
            }
            set {
                this.schemeDataURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string schemeURI {
            get {
                return this.schemeURIField;
            }
            set {
                this.schemeURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.MeasureType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class MeasureType {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class QuantityType {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.DescriptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.NoteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.TextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.SequencedTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class TextType {
        
        private string languageIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oagis.NameType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9/unqualifieddatatypes/1.1")]
    public partial class NameType {
        
        private string languageIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
