//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Oagis {
    using System.Xml.Serialization;
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CodeType", Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Code", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class CodeType : UnqualifiedDataTypes.CodeType {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Description", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class DescriptionType : UnqualifiedDataTypes.TextType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SequencedTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TextType", Namespace="http://www.openapplications.org/oagis/9")]
    public partial class TextType : UnqualifiedDataTypes.TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Reason", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class SequencedTextType : TextType {
        
        private string sequenceField;
        
        private string sequenceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string sequenceName {
            get {
                return this.sequenceNameField;
            }
            set {
                this.sequenceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NameType", Namespace="http://www.openapplications.org/oagis/9")]
    public partial class NameType : UnqualifiedDataTypes.NameType {
        
        private string sequenceField;
        
        private string sequenceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sequenceName {
            get {
                return this.sequenceNameField;
            }
            set {
                this.sequenceNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Note", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class NoteType : DescriptionType {
        
        private string authorField;
        
        private string entryDateTimeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entryDateTime {
            get {
                return this.entryDateTimeField;
            }
            set {
                this.entryDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("FromStateCode", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class StateCodeType {
        
        private string listIDField;
        
        private string listAgencyIDField;
        
        private string listAgencyNameField;
        
        private string listNameField;
        
        private string listVersionIDField;
        
        private string nameField;
        
        private string languageIDField;
        
        private string listURIField;
        
        private string listSchemeURIField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencyName {
            get {
                return this.listAgencyNameField;
            }
            set {
                this.listAgencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listURI {
            get {
                return this.listURIField;
            }
            set {
                this.listURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listSchemeURI {
            get {
                return this.listSchemeURIField;
            }
            set {
                this.listSchemeURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("UserArea", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class UserAreaType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ApplicationArea", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ApplicationAreaType {
        
        private SenderType senderField;
        
        private ReceiverType[] receiverField;
        
        private string creationDateTimeField;
        
        private SignatureType signatureField;
        
        private IdentifierType bODIDField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        public SenderType Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Receiver")]
        public ReceiverType[] Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public string CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType BODID {
            get {
                return this.bODIDField;
            }
            set {
                this.bODIDField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Sender", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class SenderType {
        
        private IdentifierType logicalIDField;
        
        private IdentifierType componentIDField;
        
        private IdentifierType taskIDField;
        
        private IdentifierType referenceIDField;
        
        private ConfirmationResponseCodeType confirmationCodeField;
        
        private IdentifierType authorizationIDField;
        
        /// <remarks/>
        public IdentifierType LogicalID {
            get {
                return this.logicalIDField;
            }
            set {
                this.logicalIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType TaskID {
            get {
                return this.taskIDField;
            }
            set {
                this.taskIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        public ConfirmationResponseCodeType ConfirmationCode {
            get {
                return this.confirmationCodeField;
            }
            set {
                this.confirmationCodeField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType AuthorizationID {
            get {
                return this.authorizationIDField;
            }
            set {
                this.authorizationIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IdentifierType", Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("AuthorizationID", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class IdentifierType : UnqualifiedDataTypes.IdentifierType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MeasureType", Namespace="http://www.openapplications.org/oagis/9")]
    public partial class MeasureType : UnqualifiedDataTypes.MeasureType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ConfirmationCode", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ConfirmationResponseCodeType : ResponseCodeType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmationResponseCodeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public partial class ResponseCodeType {
        
        private string listIDField;
        
        private string listAgencyIDField;
        
        private string listAgencyNameField;
        
        private string listNameField;
        
        private string listVersionIDField;
        
        private string nameField;
        
        private string languageIDField;
        
        private string listURIField;
        
        private string listSchemeURIField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencyName {
            get {
                return this.listAgencyNameField;
            }
            set {
                this.listAgencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listURI {
            get {
                return this.listURIField;
            }
            set {
                this.listURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string listSchemeURI {
            get {
                return this.listSchemeURIField;
            }
            set {
                this.listSchemeURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Receiver", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ReceiverType {
        
        private IdentifierType logicalIDField;
        
        private IdentifierType componentIDField;
        
        private IdentifierType[] idField;
        
        /// <remarks/>
        public IdentifierType LogicalID {
            get {
                return this.logicalIDField;
            }
            set {
                this.logicalIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType ComponentID {
            get {
                return this.componentIDField;
            }
            set {
                this.componentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID")]
        public IdentifierType[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class SignatureType {
        
        private System.Xml.XmlElement anyField;
        
        private string qualifyingAgencyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string qualifyingAgencyId {
            get {
                return this.qualifyingAgencyIdField;
            }
            set {
                this.qualifyingAgencyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("NounSuccessMessage", Namespace="http://www.openapplications.org/oagis/9", IsNullable=true)]
    public partial class SuccessMessageType {
        
        private MessageType[] processMessageField;
        
        private MessageType[] warningProcessMessageField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessMessage")]
        public MessageType[] ProcessMessage {
            get {
                return this.processMessageField;
            }
            set {
                this.processMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarningProcessMessage")]
        public MessageType[] WarningProcessMessage {
            get {
                return this.warningProcessMessageField;
            }
            set {
                this.warningProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ErrorProcessMessage", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class MessageType {
        
        private IdentifierType idField;
        
        private DescriptionType[] descriptionField;
        
        private NoteType[] noteField;
        
        private CodeType typeField;
        
        private CodeType reasonCodeField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public DescriptionType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public NoteType[] Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public CodeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public CodeType ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("BODSuccessMessage", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class BODSuccessMessageType {
        
        private MessageType[] warningProcessMessageField;
        
        private SuccessMessageType[] nounSuccessMessageField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarningProcessMessage")]
        public MessageType[] WarningProcessMessage {
            get {
                return this.warningProcessMessageField;
            }
            set {
                this.warningProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NounSuccessMessage", IsNullable=true)]
        public SuccessMessageType[] NounSuccessMessage {
            get {
                return this.nounSuccessMessageField;
            }
            set {
                this.nounSuccessMessageField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("NounFailureMessage", Namespace="http://www.openapplications.org/oagis/9", IsNullable=true)]
    public partial class FailureMessageType {
        
        private MessageType[] errorProcessMessageField;
        
        private MessageType[] warningProcessMessageField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorProcessMessage")]
        public MessageType[] ErrorProcessMessage {
            get {
                return this.errorProcessMessageField;
            }
            set {
                this.errorProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarningProcessMessage")]
        public MessageType[] WarningProcessMessage {
            get {
                return this.warningProcessMessageField;
            }
            set {
                this.warningProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("BODFailureMessage", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class BODFailureMessageType {
        
        private MessageType[] errorProcessMessageField;
        
        private MessageType[] warningProcessMessageField;
        
        private FailureMessageType[] nounFailureMessageField;
        
        private SuccessMessageType[] nounSuccessMessageField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorProcessMessage")]
        public MessageType[] ErrorProcessMessage {
            get {
                return this.errorProcessMessageField;
            }
            set {
                this.errorProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarningProcessMessage")]
        public MessageType[] WarningProcessMessage {
            get {
                return this.warningProcessMessageField;
            }
            set {
                this.warningProcessMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NounFailureMessage", IsNullable=true)]
        public FailureMessageType[] NounFailureMessage {
            get {
                return this.nounFailureMessageField;
            }
            set {
                this.nounFailureMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NounSuccessMessage", IsNullable=true)]
        public SuccessMessageType[] NounSuccessMessage {
            get {
                return this.nounSuccessMessageField;
            }
            set {
                this.nounSuccessMessageField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ActionExpression", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ActionExpressionType {
        
        private string actionCodeField;
        
        private string expressionLanguageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ActionCriteria", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ActionCriteriaType {
        
        private ActionExpressionType[] actionExpressionField;
        
        private ChangeStatusType changeStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionExpression")]
        public ActionExpressionType[] ActionExpression {
            get {
                return this.actionExpressionField;
            }
            set {
                this.actionExpressionField = value;
            }
        }
        
        /// <remarks/>
        public ChangeStatusType ChangeStatus {
            get {
                return this.changeStatusField;
            }
            set {
                this.changeStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ChangeStatus", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ChangeStatusType : StatusBasisType {
        
        private StateChangeType[] stateChangeField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StateChange")]
        public StateChangeType[] StateChange {
            get {
                return this.stateChangeField;
            }
            set {
                this.stateChangeField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("StateChange", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class StateChangeType {
        
        private StateCodeType fromStateCodeField;
        
        private StateCodeType toStateCodeField;
        
        private string changeDateTimeField;
        
        private DescriptionType[] descriptionField;
        
        private NoteType[] noteField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        public StateCodeType FromStateCode {
            get {
                return this.fromStateCodeField;
            }
            set {
                this.fromStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public StateCodeType ToStateCode {
            get {
                return this.toStateCodeField;
            }
            set {
                this.toStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ChangeDateTime {
            get {
                return this.changeDateTimeField;
            }
            set {
                this.changeDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public DescriptionType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public NoteType[] Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeStatusType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public partial class StatusBasisType {
        
        private CodeType codeField;
        
        private DescriptionType descriptionField;
        
        private string effectiveDateTimeField;
        
        private CodeType reasonCodeField;
        
        private SequencedTextType[] reasonField;
        
        /// <remarks/>
        public CodeType Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public DescriptionType Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EffectiveDateTime {
            get {
                return this.effectiveDateTimeField;
            }
            set {
                this.effectiveDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public CodeType ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reason")]
        public SequencedTextType[] Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Expression", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ExpressionType {
        
        private string expressionLanguageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseCriteria", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ResponseActionCriteriaType {
        
        private ResponseExpressionType responseExpressionField;
        
        private ChangeStatusType changeStatusField;
        
        /// <remarks/>
        public ResponseExpressionType ResponseExpression {
            get {
                return this.responseExpressionField;
            }
            set {
                this.responseExpressionField = value;
            }
        }
        
        /// <remarks/>
        public ChangeStatusType ChangeStatus {
            get {
                return this.changeStatusField;
            }
            set {
                this.changeStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseExpression", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ResponseExpressionType {
        
        private string actionCodeField;
        
        private string expressionLanguageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string expressionLanguage {
            get {
                return this.expressionLanguageField;
            }
            set {
                this.expressionLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Acknowledge", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class AcknowledgeType : ResponseVerbType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShowType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespondType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcknowledgeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public abstract partial class ResponseVerbType : VerbType {
        
        private ApplicationAreaType originalApplicationAreaField;
        
        private ResponseActionCriteriaType[] responseCriteriaField;
        
        /// <remarks/>
        public ApplicationAreaType OriginalApplicationArea {
            get {
                return this.originalApplicationAreaField;
            }
            set {
                this.originalApplicationAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseCriteria")]
        public ResponseActionCriteriaType[] ResponseCriteria {
            get {
                return this.responseCriteriaField;
            }
            set {
                this.responseCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseVerbType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShowType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespondType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcknowledgeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestVerbType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionVerbType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotifyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public abstract partial class VerbType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public abstract partial class RequestVerbType : VerbType {
        
        private ExpressionType[] expressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Expression")]
        public ExpressionType[] Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotifyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public partial class ActionVerbType : VerbType {
        
        private ActionCriteriaType[] actionCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionCriteria")]
        public ActionCriteriaType[] ActionCriteria {
            get {
                return this.actionCriteriaField;
            }
            set {
                this.actionCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Cancel", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class CancelType : ActionVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Change", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ChangeType : ActionVerbType {
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Confirm", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ConfirmType : ResponseVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Get", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class GetType : RequestVerbType {
        
        private bool uniqueIndicatorField;
        
        private bool uniqueIndicatorFieldSpecified;
        
        private string maxItemsField;
        
        private bool recordSetSaveIndicatorField;
        
        private bool recordSetSaveIndicatorFieldSpecified;
        
        private string recordSetStartNumberField;
        
        private string recordSetReferenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool uniqueIndicator {
            get {
                return this.uniqueIndicatorField;
            }
            set {
                this.uniqueIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uniqueIndicatorSpecified {
            get {
                return this.uniqueIndicatorFieldSpecified;
            }
            set {
                this.uniqueIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string maxItems {
            get {
                return this.maxItemsField;
            }
            set {
                this.maxItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recordSetSaveIndicator {
            get {
                return this.recordSetSaveIndicatorField;
            }
            set {
                this.recordSetSaveIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordSetSaveIndicatorSpecified {
            get {
                return this.recordSetSaveIndicatorFieldSpecified;
            }
            set {
                this.recordSetSaveIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetStartNumber {
            get {
                return this.recordSetStartNumberField;
            }
            set {
                this.recordSetStartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string recordSetReferenceId {
            get {
                return this.recordSetReferenceIdField;
            }
            set {
                this.recordSetReferenceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Load", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class LoadType : ActionVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Notify", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class NotifyType : ActionVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Post", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class PostType : ActionVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Process", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ProcessType : ActionVerbType {
        
        private string acknowledgeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string acknowledgeCode {
            get {
                return this.acknowledgeCodeField;
            }
            set {
                this.acknowledgeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Respond", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class RespondType : ResponseVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Show", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ShowType : ResponseVerbType {
        
        private string recordSetStartNumberField;
        
        private string recordSetCountField;
        
        private string recordSetTotalField;
        
        private bool recordSetCompleteIndicatorField;
        
        private bool recordSetCompleteIndicatorFieldSpecified;
        
        private string recordSetReferenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetStartNumber {
            get {
                return this.recordSetStartNumberField;
            }
            set {
                this.recordSetStartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetCount {
            get {
                return this.recordSetCountField;
            }
            set {
                this.recordSetCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetTotal {
            get {
                return this.recordSetTotalField;
            }
            set {
                this.recordSetTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recordSetCompleteIndicator {
            get {
                return this.recordSetCompleteIndicatorField;
            }
            set {
                this.recordSetCompleteIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordSetCompleteIndicatorSpecified {
            get {
                return this.recordSetCompleteIndicatorFieldSpecified;
            }
            set {
                this.recordSetCompleteIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string recordSetReferenceId {
            get {
                return this.recordSetReferenceIdField;
            }
            set {
                this.recordSetReferenceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Sync", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class SyncType : ActionVerbType {
        
        private string recordSetStartNumberField;
        
        private string recordSetCountField;
        
        private string recordSetTotalField;
        
        private bool recordSetCompleteIndicatorField;
        
        private bool recordSetCompleteIndicatorFieldSpecified;
        
        private string recordSetReferenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetStartNumber {
            get {
                return this.recordSetStartNumberField;
            }
            set {
                this.recordSetStartNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetCount {
            get {
                return this.recordSetCountField;
            }
            set {
                this.recordSetCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string recordSetTotal {
            get {
                return this.recordSetTotalField;
            }
            set {
                this.recordSetTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recordSetCompleteIndicator {
            get {
                return this.recordSetCompleteIndicatorField;
            }
            set {
                this.recordSetCompleteIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordSetCompleteIndicatorSpecified {
            get {
                return this.recordSetCompleteIndicatorFieldSpecified;
            }
            set {
                this.recordSetCompleteIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string recordSetReferenceId {
            get {
                return this.recordSetReferenceIdField;
            }
            set {
                this.recordSetReferenceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("Update", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class UpdateType : ActionVerbType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("BOD", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class BODType {
        
        private ApplicationAreaType originalApplicationAreaField;
        
        private DescriptionType[] descriptionField;
        
        private NoteType[] noteField;
        
        private BODFailureMessageType bODFailureMessageField;
        
        private BODSuccessMessageType bODSuccessMessageField;
        
        private BODFailureMessageType partialBODFailureMessageField;
        
        private UserAreaType userAreaField;
        
        /// <remarks/>
        public ApplicationAreaType OriginalApplicationArea {
            get {
                return this.originalApplicationAreaField;
            }
            set {
                this.originalApplicationAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public DescriptionType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public NoteType[] Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public BODFailureMessageType BODFailureMessage {
            get {
                return this.bODFailureMessageField;
            }
            set {
                this.bODFailureMessageField = value;
            }
        }
        
        /// <remarks/>
        public BODSuccessMessageType BODSuccessMessage {
            get {
                return this.bODSuccessMessageField;
            }
            set {
                this.bODSuccessMessageField = value;
            }
        }
        
        /// <remarks/>
        public BODFailureMessageType PartialBODFailureMessage {
            get {
                return this.partialBODFailureMessageField;
            }
            set {
                this.partialBODFailureMessageField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserArea {
            get {
                return this.userAreaField;
            }
            set {
                this.userAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute("ConfirmBOD", Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class ConfirmBODType : BusinessObjectDocumentType {
        
        private ConfirmBODDataAreaType dataAreaField;
        
        /// <remarks/>
        public ConfirmBODDataAreaType DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataAreaType {
        
        private ConfirmType confirmField;
        
        private BODType[] bODField;
        
        /// <remarks/>
        public ConfirmType Confirm {
            get {
                return this.confirmField;
            }
            set {
                this.confirmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BOD")]
        public BODType[] BOD {
            get {
                return this.bODField;
            }
            set {
                this.bODField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmBODType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openapplications.org/oagis/9")]
    public partial class BusinessObjectDocumentType {
        
        private ApplicationAreaType applicationAreaField;
        
        private string releaseIDField;
        
        private string versionIDField;
        
        private string systemEnvironmentCodeField;
        
        private string languageCodeField;
        
        public BusinessObjectDocumentType() {
            this.systemEnvironmentCodeField = "Production";
            this.languageCodeField = "en-US";
        }
        
        /// <remarks/>
        public ApplicationAreaType ApplicationArea {
            get {
                return this.applicationAreaField;
            }
            set {
                this.applicationAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string releaseID {
            get {
                return this.releaseIDField;
            }
            set {
                this.releaseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string versionID {
            get {
                return this.versionIDField;
            }
            set {
                this.versionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Production")]
        public string systemEnvironmentCode {
            get {
                return this.systemEnvironmentCodeField;
            }
            set {
                this.systemEnvironmentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("en-US")]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openapplications.org/oagis/9", IsNullable=false)]
    public partial class GenSupport {
        
        private ConfirmBODType confirmBODTypeSupportField;
        
        private ConfirmBODDataAreaType confirmBODDataAreaTypeSupportField;
        
        private ConfirmBODDataAreaType bODTypeSupportField;
        
        private BusinessObjectDocumentType businessObjectDocumentTypeSupportField;
        
        private ApplicationAreaType applicationAreaTypeSupportField;
        
        private SenderType senderTypeSupportField;
        
        private ReceiverType receiverTypeSupportField;
        
        private SignatureType signatureTypeSupportField;
        
        private SuccessMessageType successMessageTypeSupportField;
        
        private FailureMessageType failureMessageTypeSupportField;
        
        private BODFailureMessageType bODFailureMessageTypeSupportField;
        
        private BODSuccessMessageType bODSuccessMessageTypeSupportField;
        
        private MessageType messageTypeSupportField;
        
        private ExpressionType expressionTypeSupportField;
        
        private ActionExpressionType actionExpressionTypeSupportField;
        
        private ActionCriteriaType actionCriteriaTypeSupportField;
        
        private ResponseActionCriteriaType responseActionCriteriaTypeSupportField;
        
        private ResponseExpressionType responseExpressionTypeSupportField;
        
        private AcknowledgeType acknowledgeTypeSupportField;
        
        private CancelType cancelTypeSupportField;
        
        private ChangeType changeTypeSupportField;
        
        private ConfirmType confirmTypeSupportField;
        
        private GetType getTypeSupportField;
        
        private LoadType loadTypeSupportField;
        
        private NotifyType notifyTypeSupportField;
        
        private PostType postTypeSupportField;
        
        private ProcessType processTypeSupportField;
        
        private RespondType respondTypeSupportField;
        
        private ShowType showTypeSupportField;
        
        private SyncType syncTypeSupportField;
        
        private UpdateType updateTypeSupportField;
        
        private VerbType verbTypeSupportField;
        
        private ActionVerbType actionVerbTypeSupportField;
        
        private RequestVerbType requestVerbTypeSupportField;
        
        private ResponseVerbType responseVerbTypeSupportField;
        
        private ChangeStatusType changeStatusTypeSupportField;
        
        private StatusBasisType statusBasisTypeSupportField;
        
        private StateChangeType stateChangeTypeSupportField;
        
        private UserAreaType userAreaTypeSupportField;
        
        private CodeType codeTypeSupportField;
        
        private IdentifierType identifierTypeSupportField;
        
        private MeasureType measureTypeSupportField;
        
        private TextType textTypeSupportField;
        
        private NameType nameTypeSupportField;
        
        private DescriptionType descriptionTypeSupportField;
        
        private NoteType noteTypeSupportField;
        
        private SequencedTextType sequencedTextTypeSupportField;
        
        private ConfirmationResponseCodeType confirmationResponseCodeTypeSupportField;
        
        private ResponseCodeType responseCodeTypeSupportField;
        
        private StateCodeType stateCodeTypeSupportField;
        
        private string dateTimeTypeSupportField;
        
        private bool indicatorTypeSupportField;
        
        private string actionCodeContentTypeSupportField;
        
        private string languageCodeContentTypeSupportField;
        
        private string responseActionCodeContentTypeSupportField;
        
        private string responseCodeContentTypeSupportField;
        
        private string stateCodeContentTypeSupportField;
        
        private string systemEnvironmentCodeContentTypeSupportField;
        
        private string integerNumericTypeSupportField;
        
        private string positiveIntegerNumericTypeSupportField;
        
        private string normalizedStringTypeSupportField;
        
        private string stringTypeSupportField;
        
        private string tokenTypeSupportField;
        
        /// <remarks/>
        public ConfirmBODType ConfirmBODTypeSupport {
            get {
                return this.confirmBODTypeSupportField;
            }
            set {
                this.confirmBODTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ConfirmBODDataAreaType ConfirmBODDataAreaTypeSupport {
            get {
                return this.confirmBODDataAreaTypeSupportField;
            }
            set {
                this.confirmBODDataAreaTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ConfirmBODDataAreaType BODTypeSupport {
            get {
                return this.bODTypeSupportField;
            }
            set {
                this.bODTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public BusinessObjectDocumentType BusinessObjectDocumentTypeSupport {
            get {
                return this.businessObjectDocumentTypeSupportField;
            }
            set {
                this.businessObjectDocumentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationAreaType ApplicationAreaTypeSupport {
            get {
                return this.applicationAreaTypeSupportField;
            }
            set {
                this.applicationAreaTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SenderType SenderTypeSupport {
            get {
                return this.senderTypeSupportField;
            }
            set {
                this.senderTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ReceiverType ReceiverTypeSupport {
            get {
                return this.receiverTypeSupportField;
            }
            set {
                this.receiverTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SignatureType SignatureTypeSupport {
            get {
                return this.signatureTypeSupportField;
            }
            set {
                this.signatureTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SuccessMessageType SuccessMessageTypeSupport {
            get {
                return this.successMessageTypeSupportField;
            }
            set {
                this.successMessageTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public FailureMessageType FailureMessageTypeSupport {
            get {
                return this.failureMessageTypeSupportField;
            }
            set {
                this.failureMessageTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public BODFailureMessageType BODFailureMessageTypeSupport {
            get {
                return this.bODFailureMessageTypeSupportField;
            }
            set {
                this.bODFailureMessageTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public BODSuccessMessageType BODSuccessMessageTypeSupport {
            get {
                return this.bODSuccessMessageTypeSupportField;
            }
            set {
                this.bODSuccessMessageTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public MessageType MessageTypeSupport {
            get {
                return this.messageTypeSupportField;
            }
            set {
                this.messageTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ExpressionType ExpressionTypeSupport {
            get {
                return this.expressionTypeSupportField;
            }
            set {
                this.expressionTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ActionExpressionType ActionExpressionTypeSupport {
            get {
                return this.actionExpressionTypeSupportField;
            }
            set {
                this.actionExpressionTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ActionCriteriaType ActionCriteriaTypeSupport {
            get {
                return this.actionCriteriaTypeSupportField;
            }
            set {
                this.actionCriteriaTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseActionCriteriaType ResponseActionCriteriaTypeSupport {
            get {
                return this.responseActionCriteriaTypeSupportField;
            }
            set {
                this.responseActionCriteriaTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseExpressionType ResponseExpressionTypeSupport {
            get {
                return this.responseExpressionTypeSupportField;
            }
            set {
                this.responseExpressionTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public AcknowledgeType AcknowledgeTypeSupport {
            get {
                return this.acknowledgeTypeSupportField;
            }
            set {
                this.acknowledgeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public CancelType CancelTypeSupport {
            get {
                return this.cancelTypeSupportField;
            }
            set {
                this.cancelTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ChangeType ChangeTypeSupport {
            get {
                return this.changeTypeSupportField;
            }
            set {
                this.changeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ConfirmType ConfirmTypeSupport {
            get {
                return this.confirmTypeSupportField;
            }
            set {
                this.confirmTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public GetType GetTypeSupport {
            get {
                return this.getTypeSupportField;
            }
            set {
                this.getTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public LoadType LoadTypeSupport {
            get {
                return this.loadTypeSupportField;
            }
            set {
                this.loadTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public NotifyType NotifyTypeSupport {
            get {
                return this.notifyTypeSupportField;
            }
            set {
                this.notifyTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public PostType PostTypeSupport {
            get {
                return this.postTypeSupportField;
            }
            set {
                this.postTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ProcessType ProcessTypeSupport {
            get {
                return this.processTypeSupportField;
            }
            set {
                this.processTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public RespondType RespondTypeSupport {
            get {
                return this.respondTypeSupportField;
            }
            set {
                this.respondTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ShowType ShowTypeSupport {
            get {
                return this.showTypeSupportField;
            }
            set {
                this.showTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SyncType SyncTypeSupport {
            get {
                return this.syncTypeSupportField;
            }
            set {
                this.syncTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public UpdateType UpdateTypeSupport {
            get {
                return this.updateTypeSupportField;
            }
            set {
                this.updateTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public VerbType VerbTypeSupport {
            get {
                return this.verbTypeSupportField;
            }
            set {
                this.verbTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ActionVerbType ActionVerbTypeSupport {
            get {
                return this.actionVerbTypeSupportField;
            }
            set {
                this.actionVerbTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public RequestVerbType RequestVerbTypeSupport {
            get {
                return this.requestVerbTypeSupportField;
            }
            set {
                this.requestVerbTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseVerbType ResponseVerbTypeSupport {
            get {
                return this.responseVerbTypeSupportField;
            }
            set {
                this.responseVerbTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ChangeStatusType ChangeStatusTypeSupport {
            get {
                return this.changeStatusTypeSupportField;
            }
            set {
                this.changeStatusTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public StatusBasisType StatusBasisTypeSupport {
            get {
                return this.statusBasisTypeSupportField;
            }
            set {
                this.statusBasisTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public StateChangeType StateChangeTypeSupport {
            get {
                return this.stateChangeTypeSupportField;
            }
            set {
                this.stateChangeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public UserAreaType UserAreaTypeSupport {
            get {
                return this.userAreaTypeSupportField;
            }
            set {
                this.userAreaTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public CodeType CodeTypeSupport {
            get {
                return this.codeTypeSupportField;
            }
            set {
                this.codeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType IdentifierTypeSupport {
            get {
                return this.identifierTypeSupportField;
            }
            set {
                this.identifierTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public MeasureType MeasureTypeSupport {
            get {
                return this.measureTypeSupportField;
            }
            set {
                this.measureTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public TextType TextTypeSupport {
            get {
                return this.textTypeSupportField;
            }
            set {
                this.textTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public NameType NameTypeSupport {
            get {
                return this.nameTypeSupportField;
            }
            set {
                this.nameTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public DescriptionType DescriptionTypeSupport {
            get {
                return this.descriptionTypeSupportField;
            }
            set {
                this.descriptionTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public NoteType NoteTypeSupport {
            get {
                return this.noteTypeSupportField;
            }
            set {
                this.noteTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public SequencedTextType SequencedTextTypeSupport {
            get {
                return this.sequencedTextTypeSupportField;
            }
            set {
                this.sequencedTextTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ConfirmationResponseCodeType ConfirmationResponseCodeTypeSupport {
            get {
                return this.confirmationResponseCodeTypeSupportField;
            }
            set {
                this.confirmationResponseCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public ResponseCodeType ResponseCodeTypeSupport {
            get {
                return this.responseCodeTypeSupportField;
            }
            set {
                this.responseCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public StateCodeType StateCodeTypeSupport {
            get {
                return this.stateCodeTypeSupportField;
            }
            set {
                this.stateCodeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string DateTimeTypeSupport {
            get {
                return this.dateTimeTypeSupportField;
            }
            set {
                this.dateTimeTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public bool IndicatorTypeSupport {
            get {
                return this.indicatorTypeSupportField;
            }
            set {
                this.indicatorTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ActionCodeContentTypeSupport {
            get {
                return this.actionCodeContentTypeSupportField;
            }
            set {
                this.actionCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCodeContentTypeSupport {
            get {
                return this.languageCodeContentTypeSupportField;
            }
            set {
                this.languageCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseActionCodeContentTypeSupport {
            get {
                return this.responseActionCodeContentTypeSupportField;
            }
            set {
                this.responseActionCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeContentTypeSupport {
            get {
                return this.responseCodeContentTypeSupportField;
            }
            set {
                this.responseCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string StateCodeContentTypeSupport {
            get {
                return this.stateCodeContentTypeSupportField;
            }
            set {
                this.stateCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string SystemEnvironmentCodeContentTypeSupport {
            get {
                return this.systemEnvironmentCodeContentTypeSupportField;
            }
            set {
                this.systemEnvironmentCodeContentTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IntegerNumericTypeSupport {
            get {
                return this.integerNumericTypeSupportField;
            }
            set {
                this.integerNumericTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PositiveIntegerNumericTypeSupport {
            get {
                return this.positiveIntegerNumericTypeSupportField;
            }
            set {
                this.positiveIntegerNumericTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string NormalizedStringTypeSupport {
            get {
                return this.normalizedStringTypeSupportField;
            }
            set {
                this.normalizedStringTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        public string StringTypeSupport {
            get {
                return this.stringTypeSupportField;
            }
            set {
                this.stringTypeSupportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string TokenTypeSupport {
            get {
                return this.tokenTypeSupportField;
            }
            set {
                this.tokenTypeSupportField = value;
            }
        }
    }
}
